import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for the PainCave endurance training platform.",
};

export default function TermsPage() {
  return (
    <main className="py-20">
      <div className="prose prose-neutral dark:prose-invert mx-auto max-w-3xl px-4">
        <h1>Terms of Service</h1>
        <p className="lead">
          Effective date: 1 March 2026 &middot; Last updated: 2 March 2026
        </p>

        <p>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your use of the
          PainCave platform available at{" "}
          <a href="https://paincave.io">paincave.io</a> (the
          &ldquo;Service&rdquo;), operated by PainCave (&ldquo;we&rdquo;,
          &ldquo;us&rdquo;, &ldquo;our&rdquo;). By creating an account or
          using the Service, you agree to be bound by these Terms. If you do
          not agree, do not use the Service.
        </p>

        {/* ── 1. Service Description ─────────────────────────────── */}
        <h2>1. Service Description</h2>
        <p>
          PainCave is a software-as-a-service (SaaS) platform for endurance
          athletes. The Service analyses activity data from connected platforms
          (Strava, Garmin, Wahoo) to provide:
        </p>
        <ul>
          <li>
            Training load metrics (TSS, CTL, ATL, TSB) and performance tracking
          </li>
          <li>Personalised training zones and threshold detection</li>
          <li>Workout recommendations based on periodisation principles</li>
          <li>Nutrition targets (macronutrients, hydration, ride fuelling)</li>
          <li>Recovery readiness assessments (when health data is connected)</li>
        </ul>
        <p>
          All recommendations are generated by a rule-based coaching engine
          built on peer-reviewed exercise science research (Coggan, Banister,
          Seiler, et al.). PainCave does not use artificial intelligence or
          large language models to generate recommendations.
        </p>

        {/* ── 2. Important Disclaimers ───────────────────────────── */}
        <h2>2. Important Disclaimers</h2>
        <div
          style={{
            background: "var(--color-muted)",
            borderLeft: "4px solid var(--color-primary)",
            padding: "16px 20px",
            borderRadius: "0 8px 8px 0",
            marginBottom: "1.5em",
          }}
        >
          <p style={{ margin: 0 }}>
            <strong>
              Please read this section carefully before using PainCave.
            </strong>
          </p>
        </div>
        <ul>
          <li>
            <strong>Not medical advice.</strong> PainCave does not provide
            medical, health, or diagnostic advice. The Service is not a
            substitute for professional medical judgement. Always consult a
            qualified healthcare professional before starting, modifying, or
            intensifying any exercise programme, especially if you have a
            pre-existing medical condition.
          </li>
          <li>
            <strong>Not dietary advice.</strong> Nutrition targets displayed by
            PainCave are general guidelines based on published sports nutrition
            research. They do not constitute personalised dietary advice and
            should not be used to diagnose or treat any nutritional deficiency
            or medical condition. Consult a registered dietitian or nutritionist
            for individual nutrition planning.
          </li>
          <li>
            <strong>Training at your own risk.</strong> You are solely
            responsible for evaluating your fitness, health, and ability to
            perform any workout suggested by the Service. PainCave is not liable
            for any injury, illness, or adverse health outcome resulting from
            following recommendations provided by the platform.
          </li>
          <li>
            <strong>Data accuracy.</strong> Training metrics are derived from
            data synced from third-party devices and platforms. Accuracy depends
            on the quality and calibration of your devices (power meters, heart
            rate monitors, GPS). PainCave is not responsible for inaccurate
            metrics caused by faulty or uncalibrated equipment.
          </li>
        </ul>

        {/* ── 3. Eligibility ─────────────────────────────────────── */}
        <h2>3. Eligibility</h2>
        <p>
          You must be at least <strong>16 years old</strong> to create an
          account and use PainCave. By registering, you represent that you meet
          this age requirement. If you are between 16 and 18, you confirm that
          you have the consent of a parent or legal guardian.
        </p>

        {/* ── 4. Account Responsibilities ────────────────────────── */}
        <h2>4. Account Responsibilities</h2>
        <ul>
          <li>
            You are responsible for maintaining the confidentiality of your
            account credentials.
          </li>
          <li>
            Use a strong, unique password (minimum 12 characters recommended).
          </li>
          <li>
            You are responsible for all activity that occurs under your account.
          </li>
          <li>
            Notify us immediately at{" "}
            <a href="mailto:support@paincave.io">support@paincave.io</a> if you
            suspect unauthorised access to your account.
          </li>
          <li>One account per person. Account sharing is not permitted.</li>
        </ul>

        {/* ── 5. Subscriptions and Billing ───────────────────────── */}
        <h2>5. Subscriptions and Billing</h2>
        <h3>5.1 Plans</h3>
        <ul>
          <li>
            <strong>Free tier:</strong> no payment required. Includes limited
            features as described on the pricing page.
          </li>
          <li>
            <strong>Pro tier:</strong> billed monthly via Stripe at the rate
            published on our{" "}
            <a href="/pricing">pricing page</a> at the time of subscription.
          </li>
        </ul>

        <h3>5.2 Billing</h3>
        <ul>
          <li>
            All payments are processed securely by{" "}
            <a
              href="https://stripe.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              Stripe
            </a>
            . We do not store your payment card details.
          </li>
          <li>
            Your subscription renews automatically at the end of each billing
            period unless cancelled.
          </li>
          <li>
            Prices are displayed in the currency determined by Stripe based on
            your location.
          </li>
        </ul>

        <h3>5.3 Cancellation</h3>
        <ul>
          <li>
            You may cancel your subscription at any time from{" "}
            <strong>Settings → Billing</strong> or via the Stripe customer
            portal.
          </li>
          <li>
            Upon cancellation, you retain access to Pro features until the end
            of your current billing period.
          </li>
          <li>
            After the billing period ends, your account reverts to the free
            tier. Your data is not deleted.
          </li>
        </ul>

        <h3>5.4 Refunds</h3>
        <p>
          We do not offer refunds for partial billing periods. If you believe
          you have been charged in error, contact{" "}
          <a href="mailto:support@paincave.io">support@paincave.io</a> within
          14 days of the charge and we will review your case.
        </p>

        <h3>5.5 Price Changes</h3>
        <p>
          We may change subscription pricing with at least 30 days&apos; notice
          via email. Price changes will apply at the start of your next billing
          cycle after the notice period. If you do not agree with the new
          pricing, you may cancel before the change takes effect.
        </p>

        {/* ── 6. Acceptable Use ──────────────────────────────────── */}
        <h2>6. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>
            Reverse-engineer, decompile, or attempt to extract the source code
            of the Service
          </li>
          <li>
            Use automated scripts, bots, or scrapers to access the Service or
            its APIs
          </li>
          <li>Share your account credentials with others</li>
          <li>
            Attempt to gain unauthorised access to other users&apos; accounts or
            data
          </li>
          <li>
            Use the Service to transmit malicious code, spam, or unlawful
            content
          </li>
          <li>
            Interfere with or disrupt the Service&apos;s infrastructure or
            performance
          </li>
          <li>Use the Service for any unlawful purpose</li>
        </ul>
        <p>
          Violation of these terms may result in immediate account suspension or
          termination.
        </p>

        {/* ── 7. Your Data ───────────────────────────────────────── */}
        <h2>7. Your Data</h2>
        <p>
          <strong>Your data belongs to you.</strong> Activity data, health
          metrics, and profile information you provide or sync to PainCave
          remain your property. You grant us a limited, non-exclusive,
          revocable licence to process your data solely to provide and improve
          the Service.
        </p>
        <p>
          You may export all your data as JSON or delete your account and all
          associated data at any time from Settings. See our{" "}
          <a href="/privacy">Privacy Policy</a> for full details on data
          collection, processing, retention, and your GDPR rights.
        </p>

        {/* ── 8. Intellectual Property ───────────────────────────── */}
        <h2>8. Intellectual Property</h2>
        <p>
          The PainCave platform — including its design, code, brand identity,
          and coaching engine — is our intellectual property and is protected by
          applicable copyright and trademark laws.
        </p>
        <p>
          The training metrics and formulas we implement (TSS, CTL, ATL, TSB,
          IF, NP, etc.) are based on published, peer-reviewed research by
          Coggan, Allen, Banister, Seiler, and others. Our implementation of
          these formulas is original.
        </p>

        {/* ── 9. Third-Party Services ────────────────────────────── */}
        <h2>9. Third-Party Services</h2>
        <p>
          PainCave integrates with third-party services (Strava, Garmin, Wahoo,
          Stripe). These integrations are subject to the respective third
          party&apos;s terms of service and privacy policy. We are not
          responsible for the availability, accuracy, or practices of
          third-party services.
        </p>

        {/* ── 10. Service Availability ───────────────────────────── */}
        <h2>10. Service Availability</h2>
        <p>
          We aim to maintain high availability but do not guarantee uninterrupted
          access. The Service may be temporarily unavailable due to maintenance,
          updates, or circumstances beyond our control. We will make reasonable
          efforts to notify users of planned downtime in advance.
        </p>

        {/* ── 11. Limitation of Liability ────────────────────────── */}
        <h2>11. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by applicable law:
        </p>
        <ul>
          <li>
            The Service is provided <strong>&ldquo;as is&rdquo;</strong> and{" "}
            <strong>&ldquo;as available&rdquo;</strong> without warranties of
            any kind, whether express or implied, including but not limited to
            implied warranties of merchantability, fitness for a particular
            purpose, and non-infringement.
          </li>
          <li>
            We are <strong>not liable</strong> for any indirect, incidental,
            special, consequential, or punitive damages, including but not
            limited to loss of data, loss of profits, personal injury, or
            adverse health outcomes.
          </li>
          <li>
            Our total cumulative liability to you for any claims arising from or
            relating to the Service shall not exceed the total amount you paid
            to us in the 12 months preceding the claim.
          </li>
        </ul>
        <p>
          Nothing in these Terms excludes or limits liability that cannot be
          excluded or limited under applicable law (e.g., liability for fraud or
          gross negligence).
        </p>

        {/* ── 12. Indemnification ────────────────────────────────── */}
        <h2>12. Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless PainCave from any claims,
          damages, losses, or expenses (including reasonable legal fees) arising
          from: (a) your use of the Service, (b) your violation of these Terms,
          or (c) your violation of any third party&apos;s rights.
        </p>

        {/* ── 13. Termination ────────────────────────────────────── */}
        <h2>13. Termination</h2>
        <ul>
          <li>
            <strong>By you:</strong> you may delete your account at any time
            from Settings. All your data will be permanently removed within 30
            days.
          </li>
          <li>
            <strong>By us:</strong> we may suspend or terminate your account if
            you violate these Terms, with notice where practicable. In cases of
            severe abuse (e.g., attempted data breach), we may terminate
            immediately without notice.
          </li>
        </ul>
        <p>
          Upon termination, your right to use the Service ceases immediately.
          Sections 2 (Disclaimers), 11 (Limitation of Liability), and 12
          (Indemnification) survive termination.
        </p>

        {/* ── 14. Governing Law ──────────────────────────────────── */}
        <h2>14. Governing Law and Disputes</h2>
        <p>
          These Terms are governed by and construed in accordance with the laws
          of the Netherlands, without regard to its conflict of law provisions.
        </p>
        <p>
          Any dispute arising from these Terms or the Service shall first be
          attempted to be resolved through good-faith negotiation. If
          unresolved within 30 days, disputes shall be submitted to the
          competent courts of the Netherlands.
        </p>
        <p>
          If you are a consumer in the EU, you retain any mandatory consumer
          protection rights granted by the laws of your country of residence.
          You may also use the{" "}
          <a
            href="https://ec.europa.eu/consumers/odr"
            target="_blank"
            rel="noopener noreferrer"
          >
            EU Online Dispute Resolution platform
          </a>
          .
        </p>

        {/* ── 15. Changes ────────────────────────────────────────── */}
        <h2>15. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. Material changes will be
          communicated via email at least 30 days before taking effect.
          Continued use of the Service after the effective date constitutes
          acceptance of the updated Terms. If you disagree with the changes,
          you may delete your account before the effective date.
        </p>

        {/* ── 16. Severability ───────────────────────────────────── */}
        <h2>16. Severability</h2>
        <p>
          If any provision of these Terms is found to be invalid or
          unenforceable by a court of competent jurisdiction, the remaining
          provisions shall continue in full force and effect.
        </p>

        {/* ── 17. Entire Agreement ───────────────────────────────── */}
        <h2>17. Entire Agreement</h2>
        <p>
          These Terms, together with the{" "}
          <a href="/privacy">Privacy Policy</a>, constitute the entire
          agreement between you and PainCave regarding the Service and supersede
          any prior agreements or understandings.
        </p>

        {/* ── 18. Contact ────────────────────────────────────────── */}
        <h2>18. Contact</h2>
        <p>For questions about these Terms:</p>
        <ul>
          <li>
            Email:{" "}
            <a href="mailto:legal@paincave.io">legal@paincave.io</a>
          </li>
          <li>
            General support:{" "}
            <a href="mailto:support@paincave.io">support@paincave.io</a>
          </li>
          <li>
            Website:{" "}
            <a href="https://paincave.io">paincave.io</a>
          </li>
        </ul>
      </div>
    </main>
  );
}
