"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { signOut } from "next-auth/react";

export function AccountActions() {
  const router = useRouter();
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [deleting, setDeleting] = useState(false);

  async function handleDelete() {
    setDeleting(true);
    const res = await fetch("/api/account/delete", { method: "DELETE" });
    if (res.ok) {
      await signOut({ callbackUrl: "/" });
    } else {
      setDeleting(false);
      alert("Failed to delete account. Please try again.");
    }
  }

  return (
    <div className="space-y-6">
      {/* Data Export */}
      <div className="space-y-2">
        <h3 className="font-medium">Export Your Data</h3>
        <p className="text-sm text-muted-foreground">
          Download a JSON file containing all your data: profile, activities,
          metrics, nutrition targets, training plans, and more.
        </p>
        <a href="/api/account/export" download>
          <Button variant="outline">Download My Data</Button>
        </a>
      </div>

      {/* Disclaimer */}
      <div className="rounded-lg border p-4">
        <p className="text-xs text-muted-foreground">
          <strong>Disclaimer:</strong> Paincave provides training and
          nutrition recommendations based on published exercise science research.
          This is not medical or dietary advice. Consult a healthcare
          professional before starting any new training program or making
          significant changes to your diet. By using this service, you
          acknowledge that training recommendations are generated by rule-based
          algorithms, not certified coaches.
        </p>
      </div>

      {/* Delete Account */}
      <div className="space-y-2 border-t pt-6">
        <h3 className="font-medium text-destructive">Delete Account</h3>
        <p className="text-sm text-muted-foreground">
          Permanently delete your account and all associated data. This action
          cannot be undone.
        </p>
        {!showDeleteConfirm ? (
          <Button
            variant="destructive"
            onClick={() => setShowDeleteConfirm(true)}
          >
            Delete Account
          </Button>
        ) : (
          <div className="space-y-3 rounded-lg border border-destructive/50 bg-destructive/5 p-4">
            <p className="text-sm font-medium">
              Are you sure? This will permanently delete:
            </p>
            <ul className="list-inside list-disc text-sm text-muted-foreground">
              <li>Your profile and settings</li>
              <li>All synced activities and metrics</li>
              <li>Training plans and workout history</li>
              <li>Platform connections</li>
              <li>Subscription (will be canceled)</li>
            </ul>
            <div className="flex gap-3">
              <Button
                variant="destructive"
                onClick={handleDelete}
                disabled={deleting}
              >
                {deleting ? "Deleting..." : "Yes, delete my account"}
              </Button>
              <Button
                variant="outline"
                onClick={() => setShowDeleteConfirm(false)}
              >
                Cancel
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
